spring:
  profiles:
    default: dev
  thymeleaf:
    cache: false
    prefix: file:calendar-api/src/main/resources/templates/ #for update static file without rebuilding whole project
  web:
    resources:
      cache:
        period: 0
  datasource:
    url: jdbc:mysql://localhost:3306/calendar_db?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 9404JHKim@
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} #get env from Environment variables
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true

